# Generated by Django 3.2.1 on 2021-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='Subject',
            field=models.TextField(default='General'),
        ),
    ]
