# Generated by Django 3.2.1 on 2021-05-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='comments',
            name='times_rated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='posts',
            name='times_rated',
            field=models.IntegerField(default=0),
        ),
    ]
