# Generated by Django 3.2.1 on 2021-05-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_auto_20210507_0454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='times_rated',
        ),
        migrations.AddField(
            model_name='posts',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
