# Generated by Django 3.2.1 on 2021-05-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_auto_20210508_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='writer',
            new_name='rater',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='times_rated',
        ),
        migrations.AddField(
            model_name='posts',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='posts',
            name='report',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]),
        ),
    ]
